name: Running Docker Image

on:
  push:
    branches: [ main ]

jobs:
  job-one:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    
    - name: Checking
      uses: actions/checkout@v3
    
    - name: Linter
      uses: github/super-linter@v4.9.7
        
    - name: Build an image
      run: docker build . -t dockermarina02/node-web-app
      
    - name: Login into docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD  }}
            
    - name: Docker push
      run: docker push dockermarina02/node-web-app
